# Generated by Django 2.2.6 on 2019-12-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_servicing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('pedalType', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicing',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='servicing',
            name='date',
            field=models.DateField(verbose_name='service date'),
        ),
    ]
