# Generated by Django 2.2.6 on 2019-12-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_guitar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='pedals',
            field=models.ManyToManyField(to='main_app.Pedal'),
        ),
    ]
